# Generated by Django 4.2.16 on 2024-09-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('finish_date', models.DateTimeField(auto_now=True)),
                ('is_ready', models.BooleanField(default=False)),
            ],
        ),
    ]
